### ISSUE TITLE
Update glatos source

### ISSUE THREAD

**Issue by chrisholbrook** [edwardlavender/flapper#2]
DESCRIPTION and docs point to a repo for glatos source that is no longer maintained. 
The active repo for glatos source is now https://github.com/ocean-tracking-network/glatos

**Comment by edwardlavender** [comment]
Thanks! I will fix this ASAP. 

In the meantime, for other readers of this thread, you can install `flapper` without `glatos` via `devtools::install_github("edwardlavender/flapper", dependencies = "Depends")`.
